#source 'https://github.com/growingio/giospec.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '12.0'
use_frameworks!

install!'cocoapods',:deterministic_uuids=>false, :warn_for_unused_master_specs_repo=>false

workspace 'GrowingAnalytics.xcworkspace'
project 'Example'

target 'Example' do
  pod 'GrowingAnalytics/Autotracker', :path => '../'
  pod 'GrowingAnalytics/Ads', :path => '../'
  pod 'GrowingAnalytics/ABTesting', :path => '../'
  pod 'GrowingAnalytics/ImpressionTrack', :path => '../'

#  pod 'GrowingAnalytics/Tracker', :path => '../'
#  pod 'GrowingAnalytics/Hybrid', :path => '../'
#  pod 'GrowingAnalytics/Flutter', :path => '../'

  pod 'GrowingAPM'
#  pod 'GrowingAPM/UIMonitor'
#  pod 'GrowingAPM/CrashMonitor'
  pod 'GrowingAnalytics/APM', :path => '../'
  
  pod 'GrowingToolsKit', '2.0.0'

  pod 'SDCycleScrollView', '~> 1.75'
#  pod 'Bugly'
end

target 'ShareExtension' do
  pod 'GrowingAnalytics/Autotracker', :path => '../'
  pod 'GrowingAnalytics/Ads', :path => '../'
  pod 'GrowingAnalytics/ABTesting', :path => '../'
  pod 'GrowingAnalytics/ImpressionTrack', :path => '../'
  pod 'GrowingAnalytics/APM', :path => '../'
end

target 'GrowingAnalyticsTests' do
  pod 'GrowingAnalytics/Autotracker', :path => '../'
  pod 'GrowingAnalytics/Tracker', :path => '../'
  pod 'GrowingAnalytics/ImpressionTrack', :path => '../'
end

target 'GrowingAnalyticsStartTests' do
  pod 'GrowingAnalytics/Autotracker', :path => '../'
  pod 'GrowingAnalytics/Tracker', :path => '../'
end

target 'HostApplicationTests' do
  pod 'GrowingAnalytics/Autotracker', :path => '../'
  pod 'KIF', :configurations => ['Debug']
end

target 'ProtobufTests' do
  pod 'GrowingAnalytics/Autotracker', :path => '../'
end

target 'AdvertisingTests' do
  pod 'GrowingAnalytics/Autotracker', :path => '../'
  pod 'GrowingAnalytics/Ads', :path => '../'
end

target 'ABTestingTests' do
  pod 'GrowingAnalytics/Autotracker', :path => '../'
  pod 'GrowingAnalytics/ABTesting', :path => '../'
  pod 'OHHTTPStubs'
end

target 'ExampleiOS13' do
  pod 'GrowingAnalytics/Autotracker', :path => '../'
  pod 'GrowingAnalytics/Ads', :path => '../'

  # 这一行勿删，避免 Multiple commands produce 报错
  # 背景：GrowingToolsKit(version 1.0.9+) 依赖 GrowingAPM
  # 其目的在于告诉 Cocoapods 在执行 pod install 时，使用 target 'Example' 中所集成的 GrowingAPM，
  # 而不是再去集成一个新的 GrowingAPM，其将导致生成 2 个 GrowingAPM Pod Target，编译会出现 Multiple commands produce 报错
  pod 'GrowingAPM'

  pod 'GrowingToolsKit', '2.0.0'
end

target 'Example-macOS' do
  platform :osx, '11.0'
  pod 'GrowingAnalytics/Tracker', :path => '../'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
    if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
      target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
    end
  end
end
