os: osx
osx_image: xcode11.6
language: objective-c
env:
  global:
  - LANG=en_US.UTF-8
  - LC_ALL=en_US.UTF-8
  - APPNAME="Example"
  - 'DEVELOPER_NAME="iPhone Distribution: Beijing Yishu Technology Co., Ltd. (SXBU677CPT)"'
  - PROFILE_NAME="sdk_demo"
  - secure: EZE8xmWQcBcNMFVjP2wH/ipYgs86PJ4MdaiqUzabWjQu5NAhzh3yHWcaLXxXgB0zVCt3E4xxKCaBse+ccEG/5URU5tm3CPHhFwwuhPtCLHaYiUWkilzdGud8svQvlopY9QS3I/M7WVA96dla2MUFzhbN16QZFAANsoDJoT9e6YWR4mNOCkgVCeYYS1FtogVIGNFL5NNKLVN2F3WXMtINZZsIKF309DnaSAOLfEWgTgxX2QmP0S+gxG10Ewm/doM5J39nrwvNoxhITElrfNFMVjCMAQZmEBwJN/OchOQrdEuznJ5jzyNOXhGpwUGN3h9weTsuPHwbemj/GOEsK0rVvfAol002Lwl3Wq18IPJ6Yda8bYles9qqgexbNKvHQnuVJ3lnid/kSPQTqm6CrnWAqmvVz46utDVTtBsKrrJWI8I8X7+nUtIaX9XciEcMz26AoBCGbDYH2EYt3zZ/OjvbZGBY0iX0wM3y2ltI0pUBcUHW4UEzAH9QGLzGctf+7PsoedqMZSVmdttGM9ypoONScfK9xU1BiF+7A/oOce+pKCVG+YjjODcp3oOej64g/kWM/8A6jToDjfFUMH2nvfFo9Fy7gx/2kouJAYcFBHnbXOv9aLjcHvofwI49mjT1j9NXMXFbrSzVIr7S087j88eVBqnq+eASHIYtpCcfNJpw2hA=
  - secure: RXcb5hMJbBQQdKCd+Nk7Nm371VAOyElI6KksI7Sogz3wC8o0QSICrRW8CKwaDX34nEnRHB79IA1bvx1zOZ3ZsBU07n24GYn8oJRrS5WWWYtR6xVmqH1iV9G9iewGo6PwNifiGpElhQziaM1X3hAuEE6UOiE9kJmDjc0ANyEiT0+KpiWmsBOXZ96gheLG2b0hGxrI77Zk2NA76XHkoytXx5Dq4K+jpMlMhP5C22xsX/qqhMTQqS+zFTf/SLD2JrMI6fUs2uv9J7hQxD3zsJCRFxQVtyK7Ste3CQTIihmESAN3hkxvHO3QHWEW2WpnJzPjdtVm5YDkRxnmQBCtNDk9peLPacwJFmef3NQ947pfrN+bEOxI+EgQuZEjDaly8mJerzEFN0vVPDCJ45KKjpNUEx1RntE2V99uT5+8IvpnWTucRf/+ik8GApW+B9rVrPx2t0oVcCmC1y3K0xJ4vTBK/1SHxF4FOB6NR64sE3VhVnC78SG89t4ydy0KUFdLJquIUd/8+xcIEj+1phfOZWi2ZK/1bRv5Sy0xWtOwLt1RyKK53Qx5ERwC3UY/z0urUXw8IgXXXOOnQY6P3gdtEuxE8Z855dNPqMWWd/CFppyaMZJVRoamXyJKQso/z5ZtgWDFykL8EYUQV9/1YgyNMMBPRCtm/FwwPC/psBvfvJPDG2U=
before_install:
- openssl version
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in certificates.tar.enc -d -a -out
  certificates.tar
- mkdir ./certificates
- tar xvf certificates.tar -C ./certificates
- chmod +x Scripts/add-key.sh
- chmod +x Scripts/remove-key.sh
- brew tap growingio/homebrew-oclint
- brew install oclint-growing
before_script:
- "./Scripts/add-key.sh"
script:
- set -o pipefail
- xcodebuild -workspace GrowingAnalytics.xcworkspace -scheme Example -configuration Release -sdk iphonesimulator -arch x86_64 clean build | xcpretty -r json-compilation-database
  -o compile_commands.json
- oclint-json-compilation-database -e Pods -- -rc GIO_METHOD_ALLOW_UPPERCASE="URL,FMG3DB,TXT,UTF,STM,IMP"
  -rc GIO_CATEGORY_PREFIX=Growing -rc GIO_CLASS_PREFIX=Growing -max-priority-2=0
after_script:
- "./Scripts/remove-key.sh"
