osx_image: xcode11.6
language: objective-c

cache:
  directories:
    - /usr/local/Cellar/oclint-growing
env:
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8

before_install:
  - echo "$TRAVIS_BUILD_DIR"
  - brew tap growingio/homebrew-oclint
  - brew install oclint-growing

script:
  - set -o pipefail
  - xcodebuild -workspace GrowingAnalytics.xcworkspace -scheme GrowingAutoTracker -configuration Release -sdk iphoneos -arch armv7 clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -r json-compilation-database -o compile_commands.json
  - oclint-json-compilation-database -e Pods -- -rc GIO_METHOD_ALLOW_UPPERCASE="URL,FMG3DB,TXT,UTF,STM,IMP" -rc GIO_CATEGORY_PREFIX=Growing -rc GIO_CLASS_PREFIX=Growing -max-priority-2=15
  


