codecov:
  token: "ba961ca1-57a7-4a22-ad2e-5819eea559da"
ignore:
  - "GrowingTrackerCore/Thirdparty"  # ignore Thirdparty
  - "Example"  # ignore demo
  - "GrowingTrackerCore/NetWork/SocketRocket" # ignore websocket
