ignore:
  - "Example"
  - "GrowingTrackerCore/Thirdparty"
  - "Modules/Flutter"
  - "Services/SwiftProtobuf"
  - "Services/Protobuf/Proto/*.pbobjc.m"
  - "Services/Compression/LZ4"
  - "Services/Database/FMDB"
  - "Services/WebSocket"
  - "Package.swift"
  - "Package@swift-*.swift"