codecov:
  token: "ba961ca1-57a7-4a22-ad2e-5819eea559da"
ignore:
  - "Example"
  - "GrowingTrackerCore/Thirdparty"
  - "Modules/Protobuf/Proto/*.pbobjc.m"
  - "Services/Compression/LZ4"
  - "Services/Database/FMDB"
  - "Services/WebSocket"