name: Bug Report
description: 反馈bug问题

body:
  - type: textarea
    id: description
    attributes:
      label: 描述你的问题以及如何重现
      placeholder: |
        把你遇到的问题的发生步骤替换掉下面的内容：
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: exception-or-error
    attributes:
      label: 请提供您看到的异常或错误
      render: true

  - type: textarea
    id: environment
    attributes:
      label: 请提供您发现此错误的环境
      render: true
      placeholder: |
        OS: [e.g. MacOS] 说明操作系统
        SDK Version [e.g. 3.0.0] 相关库/包的版本
        Device: [e.g. iPhone6]

  - type: textarea
    id: other
    attributes:
      label: 其他信息