name: 'Docs Bug Report'
description: 反馈文档上的错误

body:
  - type: textarea
    id: description
    attributes:
      label: 问题描述
    validations:
      required: true

  - type: input
    id: affected-url
    attributes:
      label: 相关的URL链接

  - type: textarea
    id: screenshot
    attributes:
      label: 提供一份截图以供我们快速定位

  - type: textarea
    id: browser-info
    attributes:
      label: 这是浏览器特有的问题吗?如果是，请描述下设备、浏览器版本相关信息。
      render: true
