// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event_v3.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

#import <stdatomic.h>

#import "Services/Protobuf/Proto/GrowingEvent.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - GrowingPBEventV3Root

@implementation GrowingPBEventV3Root

// No extensions in the file and no imports, so no need to generate
// +extensionRegistry.

@end

#pragma mark - GrowingPBEventV3Root_FileDescriptor

static GPBFileDescriptor *GrowingPBEventV3Root_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"io.growing.tunnel.protocol"
                                                 objcPrefix:@"GrowingPB"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - Enum GrowingPBEventType

GPBEnumDescriptor *GrowingPBEventType_EnumDescriptor(void) {
  static _Atomic(GPBEnumDescriptor*) descriptor = nil;
  if (!descriptor) {
    static const char *valueNames =
        "Visit\000Custom\000VisitorAttributes\000LoginUser"
        "Attributes\000ConversionVariables\000AppClosed"
        "\000Page\000PageAttributes\000ViewClick\000ViewChang"
        "e\000FormSubmit\000Activate\000";
    static const int32_t values[] = {
        GrowingPBEventType_Visit,
        GrowingPBEventType_Custom,
        GrowingPBEventType_VisitorAttributes,
        GrowingPBEventType_LoginUserAttributes,
        GrowingPBEventType_ConversionVariables,
        GrowingPBEventType_AppClosed,
        GrowingPBEventType_Page,
        GrowingPBEventType_PageAttributes,
        GrowingPBEventType_ViewClick,
        GrowingPBEventType_ViewChange,
        GrowingPBEventType_FormSubmit,
        GrowingPBEventType_Activate,
    };
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(GrowingPBEventType)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:GrowingPBEventType_IsValidValue];
    GPBEnumDescriptor *expected = nil;
    if (!atomic_compare_exchange_strong(&descriptor, &expected, worker)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL GrowingPBEventType_IsValidValue(int32_t value__) {
  switch (value__) {
    case GrowingPBEventType_Visit:
    case GrowingPBEventType_Custom:
    case GrowingPBEventType_VisitorAttributes:
    case GrowingPBEventType_LoginUserAttributes:
    case GrowingPBEventType_ConversionVariables:
    case GrowingPBEventType_AppClosed:
    case GrowingPBEventType_Page:
    case GrowingPBEventType_PageAttributes:
    case GrowingPBEventType_ViewClick:
    case GrowingPBEventType_ViewChange:
    case GrowingPBEventType_FormSubmit:
    case GrowingPBEventType_Activate:
      return YES;
    default:
      return NO;
  }
}

#pragma mark - GrowingPBEventV3Dto

@implementation GrowingPBEventV3Dto

@dynamic deviceId;
@dynamic userId;
@dynamic sessionId;
@dynamic dataSourceId;
@dynamic eventType;
@dynamic platform;
@dynamic timestamp;
@dynamic domain;
@dynamic path;
@dynamic query;
@dynamic title;
@dynamic referralPage;
@dynamic eventSequenceId;
@dynamic screenHeight;
@dynamic screenWidth;
@dynamic language;
@dynamic sdkVersion;
@dynamic appVersion;
@dynamic extraSdk, extraSdk_Count;
@dynamic eventName;
@dynamic attributes, attributes_Count;
@dynamic hasResourceItem, resourceItem;
@dynamic protocolType;
@dynamic textValue;
@dynamic xpath;
@dynamic index;
@dynamic hyperlink;
@dynamic URLScheme;
@dynamic appState;
@dynamic networkState;
@dynamic appChannel;
@dynamic pageName;
@dynamic platformVersion;
@dynamic deviceBrand;
@dynamic deviceModel;
@dynamic deviceType;
@dynamic operatingSystem;
@dynamic appName;
@dynamic latitude;
@dynamic longitude;
@dynamic imei;
@dynamic androidId;
@dynamic oaid;
@dynamic googleAdvertisingId;
@dynamic idfa;
@dynamic idfv;
@dynamic orientation;
@dynamic projectKey;
@dynamic sendTime;
@dynamic userKey;
@dynamic xcontent;
@dynamic timezoneOffset;

typedef struct GrowingPBEventV3Dto__storage_ {
  uint32_t _has_storage_[2];
  GrowingPBEventType eventType;
  int32_t eventSequenceId;
  int32_t screenHeight;
  int32_t screenWidth;
  int32_t index;
  NSString *deviceId;
  NSString *userId;
  NSString *sessionId;
  NSString *dataSourceId;
  NSString *platform;
  NSString *domain;
  NSString *path;
  NSString *query;
  NSString *title;
  NSString *referralPage;
  NSString *language;
  NSString *sdkVersion;
  NSString *appVersion;
  NSMutableDictionary *extraSdk;
  NSString *eventName;
  NSMutableDictionary *attributes;
  GrowingPBResourceItem *resourceItem;
  NSString *protocolType;
  NSString *textValue;
  NSString *xpath;
  NSString *hyperlink;
  NSString *URLScheme;
  NSString *appState;
  NSString *networkState;
  NSString *appChannel;
  NSString *pageName;
  NSString *platformVersion;
  NSString *deviceBrand;
  NSString *deviceModel;
  NSString *deviceType;
  NSString *operatingSystem;
  NSString *appName;
  NSString *imei;
  NSString *androidId;
  NSString *oaid;
  NSString *googleAdvertisingId;
  NSString *idfa;
  NSString *idfv;
  NSString *orientation;
  NSString *projectKey;
  NSString *userKey;
  NSString *xcontent;
  NSString *timezoneOffset;
  int64_t timestamp;
  double latitude;
  double longitude;
  int64_t sendTime;
} GrowingPBEventV3Dto__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "deviceId",
        .dataTypeSpecific.className = NULL,
        .number = GrowingPBEventV3Dto_FieldNumber_DeviceId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(GrowingPBEventV3Dto__storage_, deviceId),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "userId",
        .dataTypeSpecific.className = NULL,
        .number = GrowingPBEventV3Dto_FieldNumber_UserId,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(GrowingPBEventV3Dto__storage_, userId),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "sessionId",
        .dataTypeSpecific.className = NULL,
        .number = GrowingPBEventV3Dto_FieldNumber_SessionId,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(GrowingPBEventV3Dto__storage_, sessionId),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "dataSourceId",
        .dataTypeSpecific.className = NULL,
        .number = GrowingPBEventV3Dto_FieldNumber_DataSourceId,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(GrowingPBEventV3Dto__storage_, dataSourceId),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "eventType",
        .dataTypeSpecific.enumDescFunc = GrowingPBEventType_EnumDescriptor,
        .number = GrowingPBEventV3Dto_FieldNumber_EventType,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(GrowingPBEventV3Dto__storage_, eventType),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldHasEnumDescriptor),
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "platform",
        .dataTypeSpecific.className = NULL,
        .number = GrowingPBEventV3Dto_FieldNumber_Platform,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(GrowingPBEventV3Dto__storage_, platform),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "timestamp",
        .dataTypeSpecific.className = NULL,
        .number = GrowingPBEventV3Dto_FieldNumber_Timestamp,
        .hasIndex = 6,
        .offset = (uint32_t)offsetof(GrowingPBEventV3Dto__storage_, timestamp),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "domain",
        .dataTypeSpecific.className = NULL,
        .number = GrowingPBEventV3Dto_FieldNumber_Domain,
        .hasIndex = 7,
        .offset = (uint32_t)offsetof(GrowingPBEventV3Dto__storage_, domain),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "path",
        .dataTypeSpecific.className = NULL,
        .number = GrowingPBEventV3Dto_FieldNumber_Path,
        .hasIndex = 8,
        .offset = (uint32_t)offsetof(GrowingPBEventV3Dto__storage_, path),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "query",
        .dataTypeSpecific.className = NULL,
        .number = GrowingPBEventV3Dto_FieldNumber_Query,
        .hasIndex = 9,
        .offset = (uint32_t)offsetof(GrowingPBEventV3Dto__storage_, query),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "title",
        .dataTypeSpecific.className = NULL,
        .number = GrowingPBEventV3Dto_FieldNumber_Title,
        .hasIndex = 10,
        .offset = (uint32_t)offsetof(GrowingPBEventV3Dto__storage_, title),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "referralPage",
        .dataTypeSpecific.className = NULL,
        .number = GrowingPBEventV3Dto_FieldNumber_ReferralPage,
        .hasIndex = 11,
        .offset = (uint32_t)offsetof(GrowingPBEventV3Dto__storage_, referralPage),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "eventSequenceId",
        .dataTypeSpecific.className = NULL,
        .number = GrowingPBEventV3Dto_FieldNumber_EventSequenceId,
        .hasIndex = 12,
        .offset = (uint32_t)offsetof(GrowingPBEventV3Dto__storage_, eventSequenceId),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "screenHeight",
        .dataTypeSpecific.className = NULL,
        .number = GrowingPBEventV3Dto_FieldNumber_ScreenHeight,
        .hasIndex = 13,
        .offset = (uint32_t)offsetof(GrowingPBEventV3Dto__storage_, screenHeight),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "screenWidth",
        .dataTypeSpecific.className = NULL,
        .number = GrowingPBEventV3Dto_FieldNumber_ScreenWidth,
        .hasIndex = 14,
        .offset = (uint32_t)offsetof(GrowingPBEventV3Dto__storage_, screenWidth),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "language",
        .dataTypeSpecific.className = NULL,
        .number = GrowingPBEventV3Dto_FieldNumber_Language,
        .hasIndex = 15,
        .offset = (uint32_t)offsetof(GrowingPBEventV3Dto__storage_, language),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "sdkVersion",
        .dataTypeSpecific.className = NULL,
        .number = GrowingPBEventV3Dto_FieldNumber_SdkVersion,
        .hasIndex = 16,
        .offset = (uint32_t)offsetof(GrowingPBEventV3Dto__storage_, sdkVersion),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "appVersion",
        .dataTypeSpecific.className = NULL,
        .number = GrowingPBEventV3Dto_FieldNumber_AppVersion,
        .hasIndex = 17,
        .offset = (uint32_t)offsetof(GrowingPBEventV3Dto__storage_, appVersion),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "extraSdk",
        .dataTypeSpecific.className = NULL,
        .number = GrowingPBEventV3Dto_FieldNumber_ExtraSdk,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(GrowingPBEventV3Dto__storage_, extraSdk),
        .flags = GPBFieldMapKeyString,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "eventName",
        .dataTypeSpecific.className = NULL,
        .number = GrowingPBEventV3Dto_FieldNumber_EventName,
        .hasIndex = 18,
        .offset = (uint32_t)offsetof(GrowingPBEventV3Dto__storage_, eventName),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "attributes",
        .dataTypeSpecific.className = NULL,
        .number = GrowingPBEventV3Dto_FieldNumber_Attributes,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(GrowingPBEventV3Dto__storage_, attributes),
        .flags = GPBFieldMapKeyString,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "resourceItem",
        .dataTypeSpecific.className = GPBStringifySymbol(GrowingPBResourceItem),
        .number = GrowingPBEventV3Dto_FieldNumber_ResourceItem,
        .hasIndex = 19,
        .offset = (uint32_t)offsetof(GrowingPBEventV3Dto__storage_, resourceItem),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "protocolType",
        .dataTypeSpecific.className = NULL,
        .number = GrowingPBEventV3Dto_FieldNumber_ProtocolType,
        .hasIndex = 20,
        .offset = (uint32_t)offsetof(GrowingPBEventV3Dto__storage_, protocolType),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "textValue",
        .dataTypeSpecific.className = NULL,
        .number = GrowingPBEventV3Dto_FieldNumber_TextValue,
        .hasIndex = 21,
        .offset = (uint32_t)offsetof(GrowingPBEventV3Dto__storage_, textValue),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "xpath",
        .dataTypeSpecific.className = NULL,
        .number = GrowingPBEventV3Dto_FieldNumber_Xpath,
        .hasIndex = 22,
        .offset = (uint32_t)offsetof(GrowingPBEventV3Dto__storage_, xpath),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "index",
        .dataTypeSpecific.className = NULL,
        .number = GrowingPBEventV3Dto_FieldNumber_Index,
        .hasIndex = 23,
        .offset = (uint32_t)offsetof(GrowingPBEventV3Dto__storage_, index),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "hyperlink",
        .dataTypeSpecific.className = NULL,
        .number = GrowingPBEventV3Dto_FieldNumber_Hyperlink,
        .hasIndex = 24,
        .offset = (uint32_t)offsetof(GrowingPBEventV3Dto__storage_, hyperlink),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "URLScheme",
        .dataTypeSpecific.className = NULL,
        .number = GrowingPBEventV3Dto_FieldNumber_URLScheme,
        .hasIndex = 25,
        .offset = (uint32_t)offsetof(GrowingPBEventV3Dto__storage_, URLScheme),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "appState",
        .dataTypeSpecific.className = NULL,
        .number = GrowingPBEventV3Dto_FieldNumber_AppState,
        .hasIndex = 26,
        .offset = (uint32_t)offsetof(GrowingPBEventV3Dto__storage_, appState),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "networkState",
        .dataTypeSpecific.className = NULL,
        .number = GrowingPBEventV3Dto_FieldNumber_NetworkState,
        .hasIndex = 27,
        .offset = (uint32_t)offsetof(GrowingPBEventV3Dto__storage_, networkState),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "appChannel",
        .dataTypeSpecific.className = NULL,
        .number = GrowingPBEventV3Dto_FieldNumber_AppChannel,
        .hasIndex = 28,
        .offset = (uint32_t)offsetof(GrowingPBEventV3Dto__storage_, appChannel),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "pageName",
        .dataTypeSpecific.className = NULL,
        .number = GrowingPBEventV3Dto_FieldNumber_PageName,
        .hasIndex = 29,
        .offset = (uint32_t)offsetof(GrowingPBEventV3Dto__storage_, pageName),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "platformVersion",
        .dataTypeSpecific.className = NULL,
        .number = GrowingPBEventV3Dto_FieldNumber_PlatformVersion,
        .hasIndex = 30,
        .offset = (uint32_t)offsetof(GrowingPBEventV3Dto__storage_, platformVersion),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "deviceBrand",
        .dataTypeSpecific.className = NULL,
        .number = GrowingPBEventV3Dto_FieldNumber_DeviceBrand,
        .hasIndex = 31,
        .offset = (uint32_t)offsetof(GrowingPBEventV3Dto__storage_, deviceBrand),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "deviceModel",
        .dataTypeSpecific.className = NULL,
        .number = GrowingPBEventV3Dto_FieldNumber_DeviceModel,
        .hasIndex = 32,
        .offset = (uint32_t)offsetof(GrowingPBEventV3Dto__storage_, deviceModel),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "deviceType",
        .dataTypeSpecific.className = NULL,
        .number = GrowingPBEventV3Dto_FieldNumber_DeviceType,
        .hasIndex = 33,
        .offset = (uint32_t)offsetof(GrowingPBEventV3Dto__storage_, deviceType),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "operatingSystem",
        .dataTypeSpecific.className = NULL,
        .number = GrowingPBEventV3Dto_FieldNumber_OperatingSystem,
        .hasIndex = 34,
        .offset = (uint32_t)offsetof(GrowingPBEventV3Dto__storage_, operatingSystem),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "appName",
        .dataTypeSpecific.className = NULL,
        .number = GrowingPBEventV3Dto_FieldNumber_AppName,
        .hasIndex = 35,
        .offset = (uint32_t)offsetof(GrowingPBEventV3Dto__storage_, appName),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "latitude",
        .dataTypeSpecific.className = NULL,
        .number = GrowingPBEventV3Dto_FieldNumber_Latitude,
        .hasIndex = 36,
        .offset = (uint32_t)offsetof(GrowingPBEventV3Dto__storage_, latitude),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeDouble,
      },
      {
        .name = "longitude",
        .dataTypeSpecific.className = NULL,
        .number = GrowingPBEventV3Dto_FieldNumber_Longitude,
        .hasIndex = 37,
        .offset = (uint32_t)offsetof(GrowingPBEventV3Dto__storage_, longitude),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeDouble,
      },
      {
        .name = "imei",
        .dataTypeSpecific.className = NULL,
        .number = GrowingPBEventV3Dto_FieldNumber_Imei,
        .hasIndex = 38,
        .offset = (uint32_t)offsetof(GrowingPBEventV3Dto__storage_, imei),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "androidId",
        .dataTypeSpecific.className = NULL,
        .number = GrowingPBEventV3Dto_FieldNumber_AndroidId,
        .hasIndex = 39,
        .offset = (uint32_t)offsetof(GrowingPBEventV3Dto__storage_, androidId),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "oaid",
        .dataTypeSpecific.className = NULL,
        .number = GrowingPBEventV3Dto_FieldNumber_Oaid,
        .hasIndex = 40,
        .offset = (uint32_t)offsetof(GrowingPBEventV3Dto__storage_, oaid),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "googleAdvertisingId",
        .dataTypeSpecific.className = NULL,
        .number = GrowingPBEventV3Dto_FieldNumber_GoogleAdvertisingId,
        .hasIndex = 41,
        .offset = (uint32_t)offsetof(GrowingPBEventV3Dto__storage_, googleAdvertisingId),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "idfa",
        .dataTypeSpecific.className = NULL,
        .number = GrowingPBEventV3Dto_FieldNumber_Idfa,
        .hasIndex = 42,
        .offset = (uint32_t)offsetof(GrowingPBEventV3Dto__storage_, idfa),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "idfv",
        .dataTypeSpecific.className = NULL,
        .number = GrowingPBEventV3Dto_FieldNumber_Idfv,
        .hasIndex = 43,
        .offset = (uint32_t)offsetof(GrowingPBEventV3Dto__storage_, idfv),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "orientation",
        .dataTypeSpecific.className = NULL,
        .number = GrowingPBEventV3Dto_FieldNumber_Orientation,
        .hasIndex = 44,
        .offset = (uint32_t)offsetof(GrowingPBEventV3Dto__storage_, orientation),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "projectKey",
        .dataTypeSpecific.className = NULL,
        .number = GrowingPBEventV3Dto_FieldNumber_ProjectKey,
        .hasIndex = 45,
        .offset = (uint32_t)offsetof(GrowingPBEventV3Dto__storage_, projectKey),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "sendTime",
        .dataTypeSpecific.className = NULL,
        .number = GrowingPBEventV3Dto_FieldNumber_SendTime,
        .hasIndex = 46,
        .offset = (uint32_t)offsetof(GrowingPBEventV3Dto__storage_, sendTime),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "userKey",
        .dataTypeSpecific.className = NULL,
        .number = GrowingPBEventV3Dto_FieldNumber_UserKey,
        .hasIndex = 47,
        .offset = (uint32_t)offsetof(GrowingPBEventV3Dto__storage_, userKey),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "xcontent",
        .dataTypeSpecific.className = NULL,
        .number = GrowingPBEventV3Dto_FieldNumber_Xcontent,
        .hasIndex = 48,
        .offset = (uint32_t)offsetof(GrowingPBEventV3Dto__storage_, xcontent),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "timezoneOffset",
        .dataTypeSpecific.className = NULL,
        .number = GrowingPBEventV3Dto_FieldNumber_TimezoneOffset,
        .hasIndex = 49,
        .offset = (uint32_t)offsetof(GrowingPBEventV3Dto__storage_, timezoneOffset),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GrowingPBEventV3Dto class]
                                     rootClass:[GrowingPBEventV3Root class]
                                          file:GrowingPBEventV3Root_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(GrowingPBEventV3Dto__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\001\037!!!\246\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t GrowingPBEventV3Dto_EventType_RawValue(GrowingPBEventV3Dto *message) {
  GPBDescriptor *descriptor = [GrowingPBEventV3Dto descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:GrowingPBEventV3Dto_FieldNumber_EventType];
  return GPBGetMessageInt32Field(message, field);
}

void SetGrowingPBEventV3Dto_EventType_RawValue(GrowingPBEventV3Dto *message, int32_t value) {
  GPBDescriptor *descriptor = [GrowingPBEventV3Dto descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:GrowingPBEventV3Dto_FieldNumber_EventType];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}

#pragma mark - GrowingPBResourceItem

@implementation GrowingPBResourceItem

@dynamic id_p;
@dynamic key;
@dynamic attributes, attributes_Count;

typedef struct GrowingPBResourceItem__storage_ {
  uint32_t _has_storage_[1];
  NSString *id_p;
  NSString *key;
  NSMutableDictionary *attributes;
} GrowingPBResourceItem__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "id_p",
        .dataTypeSpecific.className = NULL,
        .number = GrowingPBResourceItem_FieldNumber_Id_p,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(GrowingPBResourceItem__storage_, id_p),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "key",
        .dataTypeSpecific.className = NULL,
        .number = GrowingPBResourceItem_FieldNumber_Key,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(GrowingPBResourceItem__storage_, key),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "attributes",
        .dataTypeSpecific.className = NULL,
        .number = GrowingPBResourceItem_FieldNumber_Attributes,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(GrowingPBResourceItem__storage_, attributes),
        .flags = GPBFieldMapKeyString,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GrowingPBResourceItem class]
                                     rootClass:[GrowingPBEventV3Root class]
                                          file:GrowingPBEventV3Root_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(GrowingPBResourceItem__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - GrowingPBEventV3List

@implementation GrowingPBEventV3List

@dynamic valuesArray, valuesArray_Count;

typedef struct GrowingPBEventV3List__storage_ {
  uint32_t _has_storage_[1];
  NSMutableArray *valuesArray;
} GrowingPBEventV3List__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "valuesArray",
        .dataTypeSpecific.className = GPBStringifySymbol(GrowingPBEventV3Dto),
        .number = GrowingPBEventV3List_FieldNumber_ValuesArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(GrowingPBEventV3List__storage_, valuesArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GrowingPBEventV3List class]
                                     rootClass:[GrowingPBEventV3Root class]
                                          file:GrowingPBEventV3Root_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(GrowingPBEventV3List__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
