source 'https://github.com/growingio/giospec.git'
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/aliyun/aliyun-specs.git'

use_frameworks!

install!'cocoapods',:deterministic_uuids=>false
platform :ios, '8.0'

target 'GrowingIO_Example' do
  
  workspace 'GrowingIO.xcworkspace'
  pod 'GrowingIO', :path => '../'
  pod 'SDCycleScrollView', '~> 1.75'
  pod 'MJRefresh'
  pod 'MBProgressHUD'
  pod 'Bugly'
  pod 'AlicloudPush', '~> 1.9.8'

end

target 'GrowingIO_ExampleTests' do
   
   pod 'KIF', :configurations => ['Debug']
   
end

target 'GrowingTrackerUnitTest' do
  
   project 'GrowingTracker/GrowingTracker.xcodeproj'
   pod 'KIF', :configurations => ['Debug']
   pod 'OCMock', '3.5', :configurations => ['Debug']
   
end
