name: Draft Release With Tag

on: workflow_dispatch

permissions:
  contents: write

jobs:
  publish:
    runs-on: macos-latest
    env:
      REGEX: "[0-9]+\\.[0-9]+\\.[0-9]+(-hotfix.[0-9]+)*"
      SDK_VERSION_FILE1: ./GrowingTrackerCore/GrowingRealTracker.m
      SDK_VERSION_FILE2: ./GrowingAnalytics-cdp.podspec
      SDK_VERSION_FILE3: ./GrowingAnalytics.podspec
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Conventional Changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token}}
          preset: 'angular'
          skip-version-file: 'true'
          skip-commit: 'true'
          tag-prefix: ''

      - name: Update Version
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        run: |
          sed -i '' -E "s/NSString \*const GrowingTrackerVersionName = @\"${{ env.REGEX }}\";/NSString *const GrowingTrackerVersionName = @\"${{ steps.changelog.outputs.tag }}\";/" ${{ env.SDK_VERSION_FILE1 }}
          sed -i '' -E "s/s.version          = \'${{ env.REGEX }}\'/s.version          = \'${{ steps.changelog.outputs.tag }}\'/" ${{ env.SDK_VERSION_FILE2 }}
          sed -i '' -E "s/s.version          = \'${{ env.REGEX }}\'/s.version          = \'${{ steps.changelog.outputs.tag }}\'/" ${{ env.SDK_VERSION_FILE3 }}
          git commit -am "feat: release ${{ steps.changelog.outputs.tag }}"
          git push
          git tag -d ${{ steps.changelog.outputs.tag }}
          git push origin -d tag ${{ steps.changelog.outputs.tag }}
          git tag ${{ steps.changelog.outputs.tag }}
          git push --tags

      - name: Generate xcframework
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        run: 
          sh ./scripts/generate_xcframework.sh releaseDefaultAutotracker --verbose

      - name: Archive
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        run: |
          cd ./generate
          tar -czvf GrowingAnalytics.xcframework.tar.gz ./Release
          zip -r GrowingAnalytics.xcframework.zip ./Release
      
      - name: Release
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        uses: softprops/action-gh-release@v1
        with: 
          files: |
            ${{ github.workspace }}/generate/GrowingAnalytics.xcframework.tar.gz
            ${{ github.workspace }}/generate/GrowingAnalytics.xcframework.zip
          body: ${{ steps.changelog.outputs.changelog }}
          tag_name: ${{ steps.changelog.outputs.tag }}
          name: v${{ steps.changelog.outputs.tag }}
          draft: true
