name: SPM

on:
  push:
    branches: [ master ]

jobs:
  autotracker-build-iOS:
    runs-on: macos-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Build
        run: xcodebuild build -scheme GrowingAutotracker -destination 'platform=iOS Simulator,name=iPhone 14' -quiet

  autotracker-build-catalyst:
    runs-on: macos-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Build
        run: xcodebuild build -scheme GrowingAutotracker -destination 'platform=macOS,variant=Mac Catalyst' -quiet

  tracker-build-iOS:
    runs-on: macos-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Build
        run: xcodebuild build -scheme GrowingTracker -destination 'platform=iOS Simulator,name=iPhone 14' -quiet

  tracker-build-catalyst:
    runs-on: macos-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Build
        run: xcodebuild build -scheme GrowingTracker -destination 'platform=macOS,variant=Mac Catalyst' -quiet

  tracker-build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Build
        run: xcodebuild build -scheme GrowingTracker -destination 'platform=macOS' -quiet

  ads-build-iOS:
    runs-on: macos-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Build
        run: xcodebuild build -scheme GrowingModule_Ads -destination 'platform=iOS Simulator,name=iPhone 14' -quiet

  apm-build-iOS:
    runs-on: macos-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Build
        run: xcodebuild build -scheme GrowingModule_APM -destination 'platform=iOS Simulator,name=iPhone 14' -quiet

  apm-build-catalyst:
    runs-on: macos-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Build
        run: xcodebuild build -scheme GrowingModule_APM -destination 'platform=macOS,variant=Mac Catalyst' -quiet

  hybrid-build-iOS:
    runs-on: macos-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Build
        run: xcodebuild build -scheme GrowingModule_Hybrid -destination 'platform=iOS Simulator,name=iPhone 14' -quiet

  hybrid-build-catalyst:
    runs-on: macos-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Build
        run: xcodebuild build -scheme GrowingModule_Hybrid -destination 'platform=macOS,variant=Mac Catalyst' -quiet

  imp-build-iOS:
    runs-on: macos-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Build
        run: xcodebuild build -scheme GrowingModule_ImpressionTrack -destination 'platform=iOS Simulator,name=iPhone 14' -quiet
