name: SPM

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  autotracker-build-iOS:
    runs-on: macos-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Build
        run: |
          set -o pipefail
          xcodebuild build -scheme GrowingAutotracker -destination 'platform=iOS Simulator,name=iPhone 14' \
          | xcbeautify --renderer github-actions

  autotracker-build-catalyst:
    runs-on: macos-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Build
        run: |
          set -o pipefail
          xcodebuild build -scheme GrowingAutotracker -destination 'platform=macOS,variant=Mac Catalyst' \
          | xcbeautify --renderer github-actions

  tracker-build-iOS:
    runs-on: macos-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Build
        run: |
          set -o pipefail
          xcodebuild build -scheme GrowingTracker -destination 'platform=iOS Simulator,name=iPhone 14' \
          | xcbeautify --renderer github-actions

  tracker-build-catalyst:
    runs-on: macos-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Build
        run: |
          set -o pipefail
          xcodebuild build -scheme GrowingTracker -destination 'platform=macOS,variant=Mac Catalyst' \
          | xcbeautify --renderer github-actions

  tracker-build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Build
        run: |
          set -o pipefail
          xcodebuild build -scheme GrowingTracker -destination 'platform=macOS' \
          | xcbeautify --renderer github-actions

  ads-build-iOS:
    runs-on: macos-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Build
        run: |
          set -o pipefail
          xcodebuild build -scheme GrowingModule_Ads -destination 'platform=iOS Simulator,name=iPhone 14' \
          | xcbeautify --renderer github-actions

  apm-build-iOS:
    runs-on: macos-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Build
        run: |
          set -o pipefail
          xcodebuild build -scheme GrowingModule_APM -destination 'platform=iOS Simulator,name=iPhone 14' \
          | xcbeautify --renderer github-actions

  apm-build-catalyst:
    runs-on: macos-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Build
        run: |
          set -o pipefail
          xcodebuild build -scheme GrowingModule_APM -destination 'platform=macOS,variant=Mac Catalyst' \
          | xcbeautify --renderer github-actions

  hybrid-build-iOS:
    runs-on: macos-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Build
        run: |
          set -o pipefail
          xcodebuild build -scheme GrowingModule_Hybrid -destination 'platform=iOS Simulator,name=iPhone 14' \
          | xcbeautify --renderer github-actions

  hybrid-build-catalyst:
    runs-on: macos-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Build
        run: |
          set -o pipefail
          xcodebuild build -scheme GrowingModule_Hybrid -destination 'platform=macOS,variant=Mac Catalyst' \
          | xcbeautify --renderer github-actions

  imp-build-iOS:
    runs-on: macos-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Build
        run: |
          set -o pipefail
          xcodebuild build -scheme GrowingModule_ImpressionTrack -destination 'platform=iOS Simulator,name=iPhone 14' \
          | xcbeautify --renderer github-actions
