name: SPM

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  spm-build:
    strategy:
      matrix:
        target: [
          iOS,
          macOS,
          macCatalyst,
          tvOS,
          watchOS
        ]
        os: [macos-12, macos-13]
        include:
          - os: macos-12
            xcode: Xcode_14.2
          - os: macos-13
            xcode: Xcode_15.2
          - target: iOS
            platform: iOS Simulator,name=iPhone 14 Pro Max
          - target: macOS
            platform: macOS
          - target: macCatalyst
            platform: macOS,variant=Mac Catalyst
          - target: tvOS
            platform: tvOS Simulator,name=Apple TV
          - target: watchOS
            platform: watchOS Simulator,name=Apple Watch Ultra (49mm)
          - scheme: GrowingAnalytics-Package
            target: iOS
          - scheme: GrowingAutotracker
            target: macCatalyst
          - scheme: GrowingAutotracker
            target: tvOS
          - scheme: GrowingTracker
            target: macOS
          - scheme: GrowingTracker
            target: watchOS
          - target: visionOS
            os: macos-14
            xcode: Xcode_15.2
            platform: visionOS Simulator,name=Apple Vision Pro
            scheme: GrowingTracker
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Xcode
        run: sudo xcode-select -switch /Applications/${{ matrix.xcode }}.app
      - name: Build
        run: |
          set -euo pipefail
          xcodebuild build -scheme ${{ matrix.scheme }} -destination 'platform=${{ matrix.platform }}' \
          | xcbeautify --renderer github-actions